In [73]:
import numpy as np
import pandas as pd

#df.columns.difference(['D'])
df = pd.DataFrame({
'CustomerID': np.arange(1, 11),
'FirstName': ['John', 'Steve', 'Anna', 'Mike', 'Emily', 'Jake', 'Laura', 'Nick', 'Olivia',
'David'],
'LastName': ['Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller',
'Wilson', 'Moore', 'Taylor'],
'Age': np.random.randint(25, 65, size=10),
'TotalPurchaseAmount': np.random.randint(100, 1000, size=10)
})
print(df)


   CustomerID FirstName  LastName  Age  TotalPurchaseAmount
0           1      John     Smith   43                  909
1           2     Steve   Johnson   57                  816
2           3      Anna  Williams   63                  422
3           4      Mike     Jones   54                  241
4           5     Emily     Brown   39                  187
5           6      Jake     Davis   63                  165
6           7     Laura    Miller   47                  424
7           8      Nick    Wilson   62                  282
8           9    Olivia     Moore   25                  740
9          10     David    Taylor   62                  443


In [62]:
import numpy as np
import pandas as pd
np.random.seed(100)
df = pd.DataFrame(np.random.randint(0,100,size=(20, 10)),
columns=list('ABCDEFGHIJ'))
n_rows, n_cols = df.shape
row_idx = np.random.randint(0, n_rows)
col_idxs = np.random.choice(n_cols, size=n_cols//2, replace=False)
df.iloc[row_idx, col_idxs] = np.nan
n_nan_remaining = 15 - len(col_idxs)
row_idxs = np.random.randint(0, n_rows, size=n_nan_remaining)
col_idxs = np.random.randint(0, n_cols, size=n_nan_remaining)
df.iloc[row_idxs, col_idxs] = np.nan
print(df)

       A   B   C     D     E     F     G     H     I     J
0    8.0  24  67  87.0  79.0  48.0  10.0  94.0  52.0  98.0
1    NaN  66  98   NaN   NaN   NaN   NaN   NaN   NaN  16.0
2    9.0  93  86   2.0  27.0   4.0  31.0   1.0  13.0  83.0
3    4.0  91  59  67.0   7.0  49.0  47.0  65.0  61.0  14.0
4   55.0  71  80   2.0  94.0  19.0  98.0  63.0  53.0  27.0
5    NaN  30  48   NaN   NaN   NaN   NaN   NaN   NaN  56.0
6    NaN  53  74   NaN   NaN   NaN   NaN   NaN   NaN  68.0
7   50.0  91  91  83.0  53.0  78.0   0.0  13.0  57.0  76.0
8    3.0  70   3  84.0  79.0  10.0  87.0  60.0   3.0  48.0
9   52.0  43  36   5.0  71.0  38.0  86.0  94.0  98.0  42.0
10   NaN  95  76   NaN   NaN   NaN   NaN   NaN   NaN  98.0
11   NaN  53  68   NaN   NaN   NaN   NaN   NaN   NaN  48.0
12   NaN  25  54   NaN   NaN   NaN   NaN   NaN   NaN  30.0
13  66.0  24  55  17.0  45.0  89.0  45.0  35.0  16.0  12.0
14  86.0  82  67  92.0  95.0  20.0  10.0   8.0  89.0  72.0
15  30.0  12  18  93.0  92.0  44.0  57.0   0.0  73.0  54

In [95]:
#1-2
df['Classification']= df['TotalPurchaseAmount'].apply(lambda value: 'Low' if value < 500 else 'High' )


In [66]:
import numpy as np
import pandas as pd
scores_cleaned = df.dropna(subset=['A', 'B', 'C', 'E', 'F', 'G', 'H', 'I', 'J'], thresh=4)

In [111]:
#1-3
def classification_func(classification, age): 
    if classification == 'Low' and age < 20: return 'Low_Young'
    elif classification == 'Low' and age > 20: return 'Low_Old'
    elif classification == 'High' and age < 20: return 'High_Young'
    elif classification == 'High' and age >= 20: return 'high_Old'
      
df['Classification_By_Age'] = np.vectorize(classification_func)(df['Classification'], df['Age'])
df

CustomerID FirstName  LastName  Age  TotalPurchaseAmount Classification  \
0           1      John     Smith   43                  909           High   
1           2     Steve   Johnson   57                  816           High   
2           3      Anna  Williams   63                  422            Low   
3           4      Mike     Jones   54                  241            Low   
4           5     Emily     Brown   39                  187            Low   
5           6      Jake     Davis   63                  165            Low   
6           7     Laura    Miller   47                  424            Low   
7           8      Nick    Wilson   62                  282            Low   
8           9    Olivia     Moore   25                  740           High   
9          10     David    Taylor   62                  443            Low   

  Classification_By_Age  
0              high_Old  
1              high_Old  
2               Low_Old  
3               Low_Old  
4               Low_Old  
5               Low_Old  
6               Low_Old  
7               Low_Old  
8              high_Old  
9               Low_Old

In [119]:
#2-2
sort_by_name = df.sort_values(['FirstName', 'LastName'])
sort_by_name

CustomerID FirstName  LastName  Age  TotalPurchaseAmount Classification  \
2           3      Anna  Williams   63                  422            Low   
9          10     David    Taylor   62                  443            Low   
4           5     Emily     Brown   39                  187            Low   
5           6      Jake     Davis   63                  165            Low   
0           1      John     Smith   43                  909           High   
6           7     Laura    Miller   47                  424            Low   
3           4      Mike     Jones   54                  241            Low   
7           8      Nick    Wilson   62                  282            Low   
8           9    Olivia     Moore   25                  740           High   
1           2     Steve   Johnson   57                  816           High   

  Classification_By_Age  
2               Low_Old  
9               Low_Old  
4               Low_Old  
5               Low_Old  
0              high_Old  
6               Low_Old  
3               Low_Old  
7               Low_Old  
8              high_Old  
1              high_Old

In [123]:
#2-3
sort_by_amount_age = df.sort_values(['TotalPurchaseAmount', 'Age'], ascending=[True, False])
sort_by_amount_age

CustomerID FirstName  LastName  Age  TotalPurchaseAmount Classification  \
5           6      Jake     Davis   63                  165            Low   
4           5     Emily     Brown   39                  187            Low   
3           4      Mike     Jones   54                  241            Low   
7           8      Nick    Wilson   62                  282            Low   
2           3      Anna  Williams   63                  422            Low   
6           7     Laura    Miller   47                  424            Low   
9          10     David    Taylor   62                  443            Low   
8           9    Olivia     Moore   25                  740           High   
1           2     Steve   Johnson   57                  816           High   
0           1      John     Smith   43                  909           High   

  Classification_By_Age  
5               Low_Old  
4               Low_Old  
3               Low_Old  
7               Low_Old  
2               Low_Old  
6               Low_Old  
9               Low_Old  
8              high_Old  
1              high_Old  
0              high_Old

In [143]:
#3-1
np.random.seed(100)
df = pd.DataFrame(np.random.randint(0,100,size=(20, 10)),                  
columns=list('ABCDEFGHIJ'))
n_rows, n_cols = df.shape
row_idx = np.random.randint(0, n_rows)
col_idxs = np.random.choice(n_cols, size=n_cols//2, replace=False)
df.iloc[row_idx, col_idxs] = np.nan
n_nan_remaining = 15 - len(col_idxs)
row_idxs = np.random.randint(0, n_rows, size=n_nan_remaining)
col_idxs = np.random.randint(0, n_cols, size=n_nan_remaining)
df.iloc[row_idxs, col_idxs] = np.nan
row_idx, col_idxs, n_nan_remaining, row_idxs, col_idxs, df

(18,
 array([0, 3, 6, 7, 3, 6, 4, 8, 6, 5]),
 10,
 array([11,  5, 12,  6, 19, 16, 18, 17,  1, 10]),
 array([0, 3, 6, 7, 3, 6, 4, 8, 6, 5]),
        A   B   C     D     E     F     G     H     I     J
 0    8.0  24  67  87.0  79.0  48.0  10.0  94.0  52.0  98.0
 1    NaN  66  98   NaN   NaN   NaN   NaN   NaN   NaN  16.0
 2    9.0  93  86   2.0  27.0   4.0  31.0   1.0  13.0  83.0
 3    4.0  91  59  67.0   7.0  49.0  47.0  65.0  61.0  14.0
 4   55.0  71  80   2.0  94.0  19.0  98.0  63.0  53.0  27.0
 5    NaN  30  48   NaN   NaN   NaN   NaN   NaN   NaN  56.0
 6    NaN  53  74   NaN   NaN   NaN   NaN   NaN   NaN  68.0
 7   50.0  91  91  83.0  53.0  78.0   0.0  13.0  57.0  76.0
 8    3.0  70   3  84.0  79.0  10.0  87.0  60.0   3.0  48.0
 9   52.0  43  36   5.0  71.0  38.0  86.0  94.0  98.0  42.0
 10   NaN  95  76   NaN   NaN   NaN   NaN   NaN   NaN  98.0
 11   NaN  53  68   NaN   NaN   NaN   NaN   NaN   NaN  48.0
 12   NaN  25  54   NaN   NaN   NaN   NaN   NaN   NaN  30.0
 13  66.0  24  55  1

In [145]:
#3-3
droped = df.dropna()
droped

A   B   C     D     E     F     G     H     I     J
0    8.0  24  67  87.0  79.0  48.0  10.0  94.0  52.0  98.0
2    9.0  93  86   2.0  27.0   4.0  31.0   1.0  13.0  83.0
3    4.0  91  59  67.0   7.0  49.0  47.0  65.0  61.0  14.0
4   55.0  71  80   2.0  94.0  19.0  98.0  63.0  53.0  27.0
7   50.0  91  91  83.0  53.0  78.0   0.0  13.0  57.0  76.0
8    3.0  70   3  84.0  79.0  10.0  87.0  60.0   3.0  48.0
9   52.0  43  36   5.0  71.0  38.0  86.0  94.0  98.0  42.0
13  66.0  24  55  17.0  45.0  89.0  45.0  35.0  16.0  12.0
14  86.0  82  67  92.0  95.0  20.0  10.0   8.0  89.0  72.0
15  30.0  12  18  93.0  92.0  44.0  57.0   0.0  73.0  54.0

In [149]:
#3-4
import random
df_filled = df.fillna(random.randint(0, 100))
df_filled


A   B   C     D     E     F     G     H     I     J
0    8.0  24  67  87.0  79.0  48.0  10.0  94.0  52.0  98.0
1   70.0  66  98  70.0  70.0  70.0  70.0  70.0  70.0  16.0
2    9.0  93  86   2.0  27.0   4.0  31.0   1.0  13.0  83.0
3    4.0  91  59  67.0   7.0  49.0  47.0  65.0  61.0  14.0
4   55.0  71  80   2.0  94.0  19.0  98.0  63.0  53.0  27.0
5   70.0  30  48  70.0  70.0  70.0  70.0  70.0  70.0  56.0
6   70.0  53  74  70.0  70.0  70.0  70.0  70.0  70.0  68.0
7   50.0  91  91  83.0  53.0  78.0   0.0  13.0  57.0  76.0
8    3.0  70   3  84.0  79.0  10.0  87.0  60.0   3.0  48.0
9   52.0  43  36   5.0  71.0  38.0  86.0  94.0  98.0  42.0
10  70.0  95  76  70.0  70.0  70.0  70.0  70.0  70.0  98.0
11  70.0  53  68  70.0  70.0  70.0  70.0  70.0  70.0  48.0
12  70.0  25  54  70.0  70.0  70.0  70.0  70.0  70.0  30.0
13  66.0  24  55  17.0  45.0  89.0  45.0  35.0  16.0  12.0
14  86.0  82  67  92.0  95.0  20.0  10.0   8.0  89.0  72.0
15  30.0  12  18  93.0  92.0  44.0  57.0   0.0  73.0  54.0
16  70.0  66  16  70.0  70.0  70.0  70.0  70.0  70.0  78.0
17  70.0  77  84  70.0  70.0  70.0  70.0  70.0  70.0  93.0
18  70.0  28  82  70.0  70.0  70.0  70.0  70.0  70.0  70.0
19  70.0  90  93  70.0  70.0  70.0  70.0  70.0  70.0  37.0

In [155]:
#3-5
df_mean = df[['C', 'D']].fillna(df[['C','D']].mean())
df_mean

C     D
0   67  87.0
1   98  53.2
2   86   2.0
3   59  67.0
4   80   2.0
5   48  53.2
6   74  53.2
7   91  83.0
8    3  84.0
9   36   5.0
10  76  53.2
11  68  53.2
12  54  53.2
13  55  17.0
14  67  92.0
15  18  93.0
16  16  53.2
17  84  53.2
18  82  53.2
19  93  53.2

In [187]:
#3-6
new_df = df.drop(columns='D').dropna(thresh=df.shape[0] - 1, axis=1)
new_df
result_df = pd.concat([new_df[['B','C']],df[['D', 'J']]], axis=1)

result_df

B   C     D     J
0   24  67  87.0  98.0
1   66  98   NaN  16.0
2   93  86   2.0  83.0
3   91  59  67.0  14.0
4   71  80   2.0  27.0
5   30  48   NaN  56.0
6   53  74   NaN  68.0
7   91  91  83.0  76.0
8   70   3  84.0  48.0
9   43  36   5.0  42.0
10  95  76   NaN  98.0
11  53  68   NaN  48.0
12  25  54   NaN  30.0
13  24  55  17.0  12.0
14  82  67  92.0  72.0
15  12  18  93.0  54.0
16  66  16   NaN  78.0
17  77  84   NaN  93.0
18  28  82   NaN   NaN
19  90  93   NaN  37.0

# 